# Generated by Django 4.2.11 on 2024-03-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='iconWeb',
            field=models.CharField(default='https://openweathermap.org/img/wn/10d@2x.png', max_length=100),
        ),
    ]
