# Generated by Django 4.2.11 on 2024-03-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_weather_app', '0002_place_iconweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.CharField(default='40', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='long',
            field=models.CharField(default='-74', max_length=20),
        ),
    ]
