# Generated by Django 4.2.11 on 2024-03-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_weather_app', '0004_place_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lastUpdated',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
