# Generated by Django 4.2.11 on 2024-03-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_weather_app', '0005_alter_place_lastupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastTimeUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='00:00:00', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.IntegerField()),
            ],
        ),
    ]
