# Generated by Django 4.2.11 on 2024-03-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_weather_app', '0006_lasttimeupdated_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasttimeupdated',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
