# Generated by Django 4.2.11 on 2024-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_weather_app', '0007_alter_lasttimeupdated_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='windIcon',
            field=models.CharField(default='strongwind.png', max_length=100),
        ),
    ]
